# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0003_auto_20170607_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='introduction_to_models.Person'),
        ),
    ]
