# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0007_auto_20170611_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='player',
            new_name='players',
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='prev_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='introduction_to_models.Club'),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tradeinfo_set_by_recommender', to='introduction_to_models.Player'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
